print("SJC23MCA2020 : A S Ananthakrishnan")
print("Batch : MCA 2023-25")
import numpy as np;
matrix_size = 3
matrix = np.random.randint(10,20, size=(matrix_size, matrix_size))
print("Original Matrix:")
print(matrix)
if np.linalg.matrix_rank(matrix) == matrix_size:
    inverse_matrix = np.linalg.inv(matrix)
    print("\nInverse Matrix:")
    print(inverse_matrix)
else:
    print("\nThe matrix is not invertible (its rank is less than the size).")
rank = np.linalg.matrix_rank(matrix)
print("\nRank of the matrix:",rank)
determinant = np.linalg.det(matrix)
print("\nDeterminant of the matrix:",determinant)
matrix_id = matrix.flatten()
print("\nMatrix as 1D Array:")
print(matrix_id)
eigenvalues,eigenvectors = np.linalg.eig(matrix)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)
